### ISSUE TITLE
Shutdown Hook Unreachable

### ISSUE THREAD

**Issue by chrisccoy** [simplesteph/kafka-streams-course#13]
https://github.com/simplesteph/kafka-streams-course/blob/8cb61b020e3a0049c9bd60236a36b0d201f145f1/word-count/src/main/java/com/github/simplesteph/udemy/kafka/streams/WordCountApp.java#L61

**Comment by simplesteph** [comment]
correct indeed
@chrisccoy do you want to submit a PR for this? can you please create two and target both master and 1.0 ?

**Comment by chrisccoy** [comment]
👍

**Comment by simplesteph** [comment]
thanks a lot for the PRs @chrisccoy ! 
Happy learning :)
