### ISSUE TITLE
Question: Where can I find the source code

### ISSUE THREAD

**Issue by anwarchk** [simplesteph/kafka-streams-course#19]
@simplesteph I am going through the `Running your first Kafka Streams Application: WordCount` part of the `Apache Kafka Series - Kafka Streams for Data Processing` on Safari and at `3:29` you are referencing `course-intro-mac-linux` script. Where can I find the source code for that ? I went through all the slides and resources, but couldn't find anything other than this repo `simplesteph/kafka-streams-course`

**Comment by anwarchk** [comment]
@simplesteph ^^^^

**Comment by simplesteph** [comment]
@anwarchk 
From Packt: " Any customer making a purchase for a Packt product (book/video/video learning paths) on Safaribooksonline.com is re-directed to the Packt website to be able to download the source files. The customers will have to register themselves (its a FREE registration) on Packt and they can download the files on their system. Let me know if this solves the query.”

**Comment by anwarchk** [comment]
@simplesteph It did work, thanks !!!
