### ISSUE TITLE
Outer pom can be added

### ISSUE THREAD

**Issue by mithuns** [simplesteph/kafka-streams-course#3]
An outer pom can be added, with module information for the directories contained within.

**Comment by simplesteph** [comment]
thanks @mithuns . Do you want to do a PR for this?

**Comment by simplesteph** [comment]
fixed by https://github.com/simplesteph/kafka-streams-course/pull/5

**Comment by mithuns** [comment]
I would have suggested adding a 
```
<build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

But this is fine too, may be later.
